# https://taskfile.dev

version: "3"

vars:
  DEV_ARGS: -c tsconfig.json -A --unstable
  PROD_ARGS: --allow-net=0.0.0.0,suggestqueries.google.com --allow-env
  GIT_BRANCH: master

tasks:
  default:
    deps: [dev]
  dev:
    cmds:
      - deno run --watch {{.DEV_ARGS}} src/egonet.ts
  test:
    cmds:
      - deno test {{.DEV_ARGS}} src/egograph.test.ts
  lint:
    cmds:
      - deno lint --unstable ./src
      - deno fmt --check ./src 
  build:
    deps: [lint, test]
    cmds:
      - denopack -i ./src/egonet.ts -d dist
  prod:
    deps: [build]
    cmds:
      - deno run {{.PROD_ARGS}} dist/egonet.js
  deploy:
    deps: [build]
    cmds:
      - fly deploy
  push:
    deps: [build]
    cmds:
      - git add .
      - read commitMessage && git commit -m "$commitMessage"
      - git push origin {{.GIT_BRANCH}}