# https://taskfile.dev

version: "3"

vars:
  DEV_ARGS: -A --unstable
  PROD_ARGS: --allow-net=0.0.0.0,suggestqueries.google.com --allow-env

tasks:
  default:
    deps: [dev]
  dev:
    cmds:
      - deno run --watch {{.DEV_ARGS}} src/egonet.ts
  test:
    cmds:
      - deno test {{.DEV_ARGS}} src/egograph.test.ts
  build:
    deps: [test]
    cmds:
      - denopack -i ./src/egonet.ts -d dist
  prod:
    deps: [build]
    cmds:
      - deno run {{.PROD_ARGS}} dist/egonet.js
  deploy:
    deps: [build]
    cmds:
      - fly deploy
